### ISSUE TITLE
Allow text to be defined in the markup

### ISSUE THREAD

**Issue by jamiewilson** [iamdanfox/typetype#15]
It would be awesome if one could pull the text content from the markup so that it would be more accessible. In my case, I'd like to allow my templating language to define it. Is there a way to pass the text from a div into typetype or does it have to be a string?

Thanks for your help and for making this available. Great work!

**Comment by iamdanfox** [comment]
You could certainly embed the typetype text in your templating framework using some kind of `data-` attribute:

``` html
<input data-typetype-text="Hello, world!" />
```

Then in your javascript, extract that attribute:

``` js
var $elem = $("input");
var content = $elem.attr("data-typetype-text");
$elem.typetype(content);
```

[(example jsFiddle)](https://jsfiddle.net/q3w3k0bh/1/)

Do you think this kind of approach might work for you or are there library improvements you had in mind?

**Comment by jamiewilson** [comment]
Cool. That makes sense. Thanks for the help!

It might be useful though, that if you initiate typetype on an element with existing text, it would automatically extract it, clear the element and then type. That way if you just need the basic typetype effect on a block of text, you can still leave it in the markup.
